### ISSUE TITLE
iOS: "Take a photo or video" crashes the app

### ISSUE THREAD

**Issue by mxmtsk** [chatwoot/chatwoot-react-native-widget#20]
If you write a message in the chat and want to select a file, iOS grants you three options:

- Pick photo
- Take photo
- Pick file

Clicking on "Take photo" crashes the app

**Comment by muhsin-k** [comment]
There is still not enough information to debug the error. Would you be able to provide a screencast of the behaviour?

**Comment by mxmtsk** [comment]
Hi @muhsin-k, I figured out that the issue simply was that I simply was missing the `NSCameraUsageDescription` key in `Info.plist`. After adding it, it worked fine.
