### ISSUE TITLE
Back Button not working on react native 0.70.6

### ISSUE THREAD

**Issue by Med-Ahmed-Kilani** [chatwoot/chatwoot-react-native-widget#26]
Each time I click on back button the app show me this error 
I tried it with react native 0.66.1 it works just perfect 
but on react native 0.70.6 give me this error 

![Simulator Screen Shot - iPhone 11 pro - 2023-01-22 at 16 08 45](https://user-images.githubusercontent.com/70693716/214010529-858a0203-9f0b-4748-93c3-7a4d1badd8d7.png)

I tried to download the latest react native webView and react native modal but no luck i checked the code on the lib and i didn't find any componentWillUnmount or anything related to the error.
just to check I also tried it on a new project also the same result 

Please if there is any solution or any idea that I can help.
Thank you <3

**Comment by muhsin-k** [comment]
@Med-Ahmed-Kilani This is a confirmed bug. We are working on it. I will make sure to update you soon.

**Comment by muhsin-k** [comment]
@Med-Ahmed-Kilani We have fixed the issue. Please update to version `0.0.10`.
