### ISSUE TITLE
duplicated Accounts with the same identifier

### ISSUE THREAD

**Issue by Med-Ahmed-Kilani** [chatwoot/chatwoot-react-native-widget#28]
each time I used a client info it create a new session with the same user info without getting the old messages and sometimes the 
client don't get the responses from the web 
but when i test it with the provided dummy data from the readme file everything works just fine.
<img width="990" alt="Screenshot 2023-02-19 at 5 30 49 PM" src="https://user-images.githubusercontent.com/70693716/219961307-4589e4d1-1440-4402-bdaa-df93f13c9833.png">
![Simulator Screen Shot - iPhone 11 pro - 2023-02-19 at 15 34 08](https://user-images.githubusercontent.com/70693716/219961323-26a07166-bd45-4dae-ac33-a6ae8d24e9ed.png)

**Comment by muhsin-k** [comment]
@Med-Ahmed-Kilani Could you please share the `user ` props?

**Comment by Med-Ahmed-Kilani** [comment]
@muhsin-k it's working just fine now idk why she behave like that the other day but i didn't change anything
