### ISSUE TITLE
Warning: WebViewComponent: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.     in WebViewComponent (created by ChatWootWidget)

### ISSUE THREAD

**Issue by AyoParadis** [chatwoot/chatwoot-react-native-widget#44]
Will there be an update to the widget anytime soon?

**Comment by remnantdotdev** [comment]
This is causing app crashes for us, can we please get this taken care of?

**Comment by AyoCodess** [comment]
> This is causing app crashes for us, can we please get this taken care of?

Exact same issue.

**Comment by muhsin-k** [comment]
@AyoCodess @myarete Fixed via #45 . Please update to the latest version 0.0.20.
